// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY4Uq21bRI2FpnXSIG4I9M2uEuNirGgxE',
    appId: '1:584373295843:web:772286de5cfb76bccc83d6',
    messagingSenderId: '584373295843',
    projectId: 'flutterbegin1',
    authDomain: 'flutterbegin1.firebaseapp.com',
    storageBucket: 'flutterbegin1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQxCZwzFdCboFiQmfMn7f8KfRjSSAv_gA',
    appId: '1:584373295843:android:b2e7120ce70e265ecc83d6',
    messagingSenderId: '584373295843',
    projectId: 'flutterbegin1',
    storageBucket: 'flutterbegin1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDar5DAsdKo9-vSrTedQIVJiKoy9OFF6E8',
    appId: '1:584373295843:ios:d66ba96b137278d4cc83d6',
    messagingSenderId: '584373295843',
    projectId: 'flutterbegin1',
    storageBucket: 'flutterbegin1.appspot.com',
    iosClientId: '584373295843-5nqade3b9ahd3ri3k4k5qa4sttmln6ed.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbegin1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDar5DAsdKo9-vSrTedQIVJiKoy9OFF6E8',
    appId: '1:584373295843:ios:5c8767bbb79bbf48cc83d6',
    messagingSenderId: '584373295843',
    projectId: 'flutterbegin1',
    storageBucket: 'flutterbegin1.appspot.com',
    iosClientId: '584373295843-r79pm34fbvgaf1c8i6jg80i95248lhf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterbegin1.RunnerTests',
  );
}
